language: node_js
sudo : required
node_js:
  - "6"
  - "8"
os:
  - linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install nginx
  - sudo service nginx start
script:
  - sudo env "PATH=$PATH" npm test
